print('非空字符串的布尔值：',bool('hello'))
print('空字符串的布尔值：',bool(''))
print('空列表的布尔值：',bool([]))
print('空列表的布尔值：',bool(list()))
print('空元组的布尔值：',bool(()))
print('空元组的布尔值：',bool(tuple()))
print('空集合的布尔值：',bool(set()))
print('空字典的布尔值：',bool({}))
print('空字典的布尔值：',bool(dict()))

print('-'*30)
print('非0数值型的布尔值：',bool(123))
print('整数0数值型的布尔值：',bool(0))
print('浮点数0.0数值型的布尔值：',bool(0.0))
print('-'*30)
s='hello'
print(list(s))

seq=range(1,10)
print(tuple(seq))
print(set(seq))
print(list(seq))